/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WelcomeImport } from './routes/welcome'
import { Route as TqueryImport } from './routes/tquery'
import { Route as GraphqlImport } from './routes/graphql'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WelcomeRoute = WelcomeImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRoute,
} as any)

const TqueryRoute = TqueryImport.update({
  id: '/tquery',
  path: '/tquery',
  getParentRoute: () => rootRoute,
} as any)

const GraphqlRoute = GraphqlImport.update({
  id: '/graphql',
  path: '/graphql',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/graphql': {
      id: '/graphql'
      path: '/graphql'
      fullPath: '/graphql'
      preLoaderRoute: typeof GraphqlImport
      parentRoute: typeof rootRoute
    }
    '/tquery': {
      id: '/tquery'
      path: '/tquery'
      fullPath: '/tquery'
      preLoaderRoute: typeof TqueryImport
      parentRoute: typeof rootRoute
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graphql': typeof GraphqlRoute
  '/tquery': typeof TqueryRoute
  '/welcome': typeof WelcomeRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graphql': typeof GraphqlRoute
  '/tquery': typeof TqueryRoute
  '/welcome': typeof WelcomeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/graphql': typeof GraphqlRoute
  '/tquery': typeof TqueryRoute
  '/welcome': typeof WelcomeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/graphql' | '/tquery' | '/welcome'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/graphql' | '/tquery' | '/welcome'
  id: '__root__' | '/' | '/graphql' | '/tquery' | '/welcome'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphqlRoute: typeof GraphqlRoute
  TqueryRoute: typeof TqueryRoute
  WelcomeRoute: typeof WelcomeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphqlRoute: GraphqlRoute,
  TqueryRoute: TqueryRoute,
  WelcomeRoute: WelcomeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/graphql",
        "/tquery",
        "/welcome"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/graphql": {
      "filePath": "graphql.tsx"
    },
    "/tquery": {
      "filePath": "tquery.tsx"
    },
    "/welcome": {
      "filePath": "welcome.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
